version: "3.8"

services:

  db:
    image: postgres:13.3-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_test
    ports:
      - 5432:5432
